/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/http';
import * as import6 from '@angular/platform-browser/animations';
import * as import7 from '@progress/kendo-angular-buttons/dist/es/button/button.module';
import * as import8 from '@progress/kendo-angular-buttons/dist/es/buttongroup/buttongroup.module';
import * as import9 from '@progress/kendo-angular-popup/dist/es/popup.module';
import * as import10 from '@progress/kendo-angular-buttons/dist/es/listbutton/list.module';
import * as import11 from '@progress/kendo-angular-buttons/dist/es/splitbutton/splitbutton.module';
import * as import12 from '@progress/kendo-angular-buttons/dist/es/dropdownbutton/dropdownbutton.module';
import * as import13 from '@progress/kendo-angular-buttons/dist/es/buttons.module';
import * as import14 from '@progress/kendo-angular-popup/dist/es/popup.service';
import * as import15 from '../../node_modules/@progress/kendo-angular-popup/dist/es/popup.component.ngfactory';
import * as import16 from './app.component.ngfactory';
import * as import17 from '@angular/animations/browser';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _APP_INITIALIZER_2:any[];
  _ApplicationInitStatus_3:import0.ApplicationInitStatus;
  _ɵf_4:import0.ɵf;
  _ApplicationRef_5:any;
  _ApplicationModule_6:import0.ApplicationModule;
  _BrowserModule_7:import3.BrowserModule;
  _ɵba_8:import4.ɵba;
  _FormsModule_9:import4.FormsModule;
  _HttpModule_10:import5.HttpModule;
  _BrowserAnimationsModule_11:import6.BrowserAnimationsModule;
  _ButtonModule_12:import7.ButtonModule;
  _ButtonGroupModule_13:import8.ButtonGroupModule;
  _PopupModule_14:import9.PopupModule;
  _ListModule_15:import10.ListModule;
  _SplitButtonModule_16:import11.SplitButtonModule;
  _DropDownButtonModule_17:import12.DropDownButtonModule;
  _ButtonsModule_18:import13.ButtonsModule;
  _AppModule_19:import1.AppModule;
  __LOCALE_ID_20:any;
  __NgLocalization_21:import2.NgLocaleLocalization;
  __Compiler_22:import0.Compiler;
  __APP_ID_23:any;
  __IterableDiffers_24:any;
  __KeyValueDiffers_25:any;
  __DomSanitizer_26:import3.ɵe;
  __Sanitizer_27:any;
  __HAMMER_GESTURE_CONFIG_28:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_29:any[];
  __EventManager_30:import3.EventManager;
  __ɵDomSharedStylesHost_31:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_32:import3.ɵDomRendererFactory2;
  __AnimationDriver_33:any;
  __ɵAnimationStyleNormalizer_34:any;
  __ɵAnimationEngine_35:import6.ɵa;
  __RendererFactory2_36:any;
  __ɵSharedStylesHost_37:any;
  __Testability_38:import0.Testability;
  __Meta_39:import3.Meta;
  __Title_40:import3.Title;
  __ɵi_41:import4.ɵi;
  __BrowserXhr_42:import5.BrowserXhr;
  __ResponseOptions_43:import5.BaseResponseOptions;
  __XSRFStrategy_44:any;
  __XHRBackend_45:import5.XHRBackend;
  __RequestOptions_46:import5.BaseRequestOptions;
  __Http_47:any;
  __PopupService_48:import14.PopupService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import15.PopupComponentNgFactory,
      import16.AppComponentNgFactory
    ]
    ,[import16.AppComponentNgFactory]);
  }
  get _LOCALE_ID_20():any {
    if ((this.__LOCALE_ID_20 == null)) { (this.__LOCALE_ID_20 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_20;
  }
  get _NgLocalization_21():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_21 == null)) { (this.__NgLocalization_21 = new import2.NgLocaleLocalization(this._LOCALE_ID_20)); }
    return this.__NgLocalization_21;
  }
  get _Compiler_22():import0.Compiler {
    if ((this.__Compiler_22 == null)) { (this.__Compiler_22 = new import0.Compiler()); }
    return this.__Compiler_22;
  }
  get _APP_ID_23():any {
    if ((this.__APP_ID_23 == null)) { (this.__APP_ID_23 = import0.ɵg()); }
    return this.__APP_ID_23;
  }
  get _IterableDiffers_24():any {
    if ((this.__IterableDiffers_24 == null)) { (this.__IterableDiffers_24 = import0.ɵl()); }
    return this.__IterableDiffers_24;
  }
  get _KeyValueDiffers_25():any {
    if ((this.__KeyValueDiffers_25 == null)) { (this.__KeyValueDiffers_25 = import0.ɵm()); }
    return this.__KeyValueDiffers_25;
  }
  get _DomSanitizer_26():import3.ɵe {
    if ((this.__DomSanitizer_26 == null)) { (this.__DomSanitizer_26 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == null)) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _HAMMER_GESTURE_CONFIG_28():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_28 == null)) { (this.__HAMMER_GESTURE_CONFIG_28 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_28;
  }
  get _EVENT_MANAGER_PLUGINS_29():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_29 == null)) { (this.__EVENT_MANAGER_PLUGINS_29 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_28)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_29;
  }
  get _EventManager_30():import3.EventManager {
    if ((this.__EventManager_30 == null)) { (this.__EventManager_30 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_29,this.parent.get(import0.NgZone))); }
    return this.__EventManager_30;
  }
  get _ɵDomSharedStylesHost_31():import3.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_31 == null)) { (this.__ɵDomSharedStylesHost_31 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_31;
  }
  get _ɵDomRendererFactory2_32():import3.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_32 == null)) { (this.__ɵDomRendererFactory2_32 = new import3.ɵDomRendererFactory2(this._EventManager_30,this._ɵDomSharedStylesHost_31)); }
    return this.__ɵDomRendererFactory2_32;
  }
  get _AnimationDriver_33():any {
    if ((this.__AnimationDriver_33 == null)) { (this.__AnimationDriver_33 = import6.ɵb()); }
    return this.__AnimationDriver_33;
  }
  get _ɵAnimationStyleNormalizer_34():any {
    if ((this.__ɵAnimationStyleNormalizer_34 == null)) { (this.__ɵAnimationStyleNormalizer_34 = import6.ɵc()); }
    return this.__ɵAnimationStyleNormalizer_34;
  }
  get _ɵAnimationEngine_35():import6.ɵa {
    if ((this.__ɵAnimationEngine_35 == null)) { (this.__ɵAnimationEngine_35 = new import6.ɵa(this._AnimationDriver_33,this._ɵAnimationStyleNormalizer_34)); }
    return this.__ɵAnimationEngine_35;
  }
  get _RendererFactory2_36():any {
    if ((this.__RendererFactory2_36 == null)) { (this.__RendererFactory2_36 = import6.ɵd(this._ɵDomRendererFactory2_32,this._ɵAnimationEngine_35,this.parent.get(import0.NgZone))); }
    return this.__RendererFactory2_36;
  }
  get _ɵSharedStylesHost_37():any {
    if ((this.__ɵSharedStylesHost_37 == null)) { (this.__ɵSharedStylesHost_37 = this._ɵDomSharedStylesHost_31); }
    return this.__ɵSharedStylesHost_37;
  }
  get _Testability_38():import0.Testability {
    if ((this.__Testability_38 == null)) { (this.__Testability_38 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_38;
  }
  get _Meta_39():import3.Meta {
    if ((this.__Meta_39 == null)) { (this.__Meta_39 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_39;
  }
  get _Title_40():import3.Title {
    if ((this.__Title_40 == null)) { (this.__Title_40 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_40;
  }
  get _ɵi_41():import4.ɵi {
    if ((this.__ɵi_41 == null)) { (this.__ɵi_41 = new import4.ɵi()); }
    return this.__ɵi_41;
  }
  get _BrowserXhr_42():import5.BrowserXhr {
    if ((this.__BrowserXhr_42 == null)) { (this.__BrowserXhr_42 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_42;
  }
  get _ResponseOptions_43():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_43 == null)) { (this.__ResponseOptions_43 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_43;
  }
  get _XSRFStrategy_44():any {
    if ((this.__XSRFStrategy_44 == null)) { (this.__XSRFStrategy_44 = import5.ɵb()); }
    return this.__XSRFStrategy_44;
  }
  get _XHRBackend_45():import5.XHRBackend {
    if ((this.__XHRBackend_45 == null)) { (this.__XHRBackend_45 = new import5.XHRBackend(this._BrowserXhr_42,this._ResponseOptions_43,this._XSRFStrategy_44)); }
    return this.__XHRBackend_45;
  }
  get _RequestOptions_46():import5.BaseRequestOptions {
    if ((this.__RequestOptions_46 == null)) { (this.__RequestOptions_46 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_46;
  }
  get _Http_47():any {
    if ((this.__Http_47 == null)) { (this.__Http_47 = import5.ɵc(this._XHRBackend_45,this._RequestOptions_46)); }
    return this.__Http_47;
  }
  get _PopupService_48():import14.PopupService {
    if ((this.__PopupService_48 == null)) { (this.__PopupService_48 = new import14.PopupService(this._ApplicationRef_5,this.componentFactoryResolver,this,this.parent.get(import14.POPUP_CONTAINER,(null as any)))); }
    return this.__PopupService_48;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import3.ɵa();
    this._APP_INITIALIZER_2 = [
      import0.ɵo,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_3 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_2);
    this._ɵf_4 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_3);
    this._ApplicationRef_5 = this._ɵf_4;
    this._ApplicationModule_6 = new import0.ApplicationModule(this._ApplicationRef_5);
    this._BrowserModule_7 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._ɵba_8 = new import4.ɵba();
    this._FormsModule_9 = new import4.FormsModule();
    this._HttpModule_10 = new import5.HttpModule();
    this._BrowserAnimationsModule_11 = new import6.BrowserAnimationsModule();
    this._ButtonModule_12 = new import7.ButtonModule();
    this._ButtonGroupModule_13 = new import8.ButtonGroupModule();
    this._PopupModule_14 = new import9.PopupModule();
    this._ListModule_15 = new import10.ListModule();
    this._SplitButtonModule_16 = new import11.SplitButtonModule();
    this._DropDownButtonModule_17 = new import12.DropDownButtonModule();
    this._ButtonsModule_18 = new import13.ButtonsModule();
    this._AppModule_19 = new import1.AppModule();
    return this._AppModule_19;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_2; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_3; }
    if ((token === import0.ɵf)) { return this._ɵf_4; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_5; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_6; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_7; }
    if ((token === import4.ɵba)) { return this._ɵba_8; }
    if ((token === import4.FormsModule)) { return this._FormsModule_9; }
    if ((token === import5.HttpModule)) { return this._HttpModule_10; }
    if ((token === import6.BrowserAnimationsModule)) { return this._BrowserAnimationsModule_11; }
    if ((token === import7.ButtonModule)) { return this._ButtonModule_12; }
    if ((token === import8.ButtonGroupModule)) { return this._ButtonGroupModule_13; }
    if ((token === import9.PopupModule)) { return this._PopupModule_14; }
    if ((token === import10.ListModule)) { return this._ListModule_15; }
    if ((token === import11.SplitButtonModule)) { return this._SplitButtonModule_16; }
    if ((token === import12.DropDownButtonModule)) { return this._DropDownButtonModule_17; }
    if ((token === import13.ButtonsModule)) { return this._ButtonsModule_18; }
    if ((token === import1.AppModule)) { return this._AppModule_19; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_20; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_21; }
    if ((token === import0.Compiler)) { return this._Compiler_22; }
    if ((token === import0.APP_ID)) { return this._APP_ID_23; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_24; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_25; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_28; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_29; }
    if ((token === import3.EventManager)) { return this._EventManager_30; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_31; }
    if ((token === import3.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_32; }
    if ((token === import17.AnimationDriver)) { return this._AnimationDriver_33; }
    if ((token === import17.ɵAnimationStyleNormalizer)) { return this._ɵAnimationStyleNormalizer_34; }
    if ((token === import17.ɵAnimationEngine)) { return this._ɵAnimationEngine_35; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_36; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_37; }
    if ((token === import0.Testability)) { return this._Testability_38; }
    if ((token === import3.Meta)) { return this._Meta_39; }
    if ((token === import3.Title)) { return this._Title_40; }
    if ((token === import4.ɵi)) { return this._ɵi_41; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_42; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_43; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_44; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_45; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_46; }
    if ((token === import5.Http)) { return this._Http_47; }
    if ((token === import14.PopupService)) { return this._PopupService_48; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_4.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_31 && this._ɵDomSharedStylesHost_31.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovTXlQb3JvamVjdHMvQW5ndWxhci9rZW5kby1hbmd1bGFyL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9NeVBvcm9qZWN0cy9Bbmd1bGFyL2tlbmRvLWFuZ3VsYXIvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
